### ISSUE TITLE
Create an initial iot edge deployment

### ISSUE THREAD

**Issue by mihaiboldeanu** [pineviewlabs/iotedge-docker#2]
As a DevOps Engineer, I want to deploy a set of Python packages using Docker for IoT Edge Development so that the deployment process is streamlined, consistent, and repeatable.

Start building a SoP for deployment using either:

- https://github.com/OceanStreamIO/iotedge-docker
- https://github.com/Azure/iotedgedev

**Acceptance Criteria:**
 - Environment Setup:

The IoT Edge development environment is set up successfully using either the OceanStreamIO/iotedge-docker or Azure/iotedgedev GitHub repositories.
Relevant documentation from the chosen repository is followed for environment setup.

 - Docker Container Creation:

A Docker container is successfully created for the Python packages.
The Docker container is configured correctly to work with IoT Edge.

 - Python Packages Deployment:

The set of Python packages is successfully deployed within the Docker container.
The deployed Python packages within the Docker container are functioning as expected.

 - Testing:

The deployment is tested in a staging environment that mimics the production environment.
All tests pass successfully, ensuring the deployment works as expected.

 - Deployment:

The Docker container with the Python packages is successfully deployed to the production environment.
The deployment to the production environment is verified and confirmed to be working as expected.

Tasks:
 - [x] Choose the Repository:

Review both the OceanStreamIO/iotedge-docker and Azure/iotedgedev GitHub repositories.
Choose the one that best fits the project requirements.

 - [ ] Follow the Setup Documentation:

Follow the setup documentation from the chosen repository to set up the IoT Edge development environment.

 - [ ] Create a Docker Container:

Write a Dockerfile to create a Docker container for the Python packages.
Configure the Docker container for IoT Edge development.

 - [ ] Deploy Python Packages:

Deploy the set of Python packages within the created Docker container.

 - [ ] Test the Deployment:

Test the deployment in a staging environment.
Ensure all tests pass and the deployment works as expected.

 - [ ] Documentation:

Document the entire process, including setup, deployment, and testing.
Ensure the documentation is clear and understandable for future reference.

**Comment by mihaiboldeanu** [comment]
Decided on using the official https://github.com/Azure/iotedgedev as it has the most up to date features

**Comment by beatfactor** [comment]
IoT Edge deployment solution repo is available here: 
- https://github.com/OceanStreamIO/oceanstream-iotedge

To simulate an Azure IoT Edge device, this docker container can be used:
- https://github.com/OceanStreamIO/iotedge-docker

Oceanstream IoT Edge module available here: 
- https://github.com/OceanStreamIO/iotedge-echosounder
